attention_head_size: 1
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 32
learning_rate: 0.03
log_gradient_flow: false
log_interval: -1
log_val_interval: null
lstm_layers: 1
max_encoder_length: 30
monotone_constaints: {}
optimizer: adamw
optimizer_params: null
output_size: 1
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    n9+9XPxLLUE=
  max_length: null
  method: standard
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    /3D/iWBDGEE=
  transformation: relu
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- time_idx
- Total Room Inventory
- Rooms Sold
- Arrival Rooms
- Compliment Rooms
- House Use
- Individual Confirm
- Occupancy %
- ARR
- Departure Rooms
- OOO Rooms
- Pax
- revenue_diff
time_varying_reals_encoder:
- time_idx
- Total Room Inventory
- Rooms Sold
- Arrival Rooms
- Compliment Rooms
- House Use
- Individual Confirm
- Occupancy %
- ARR
- Departure Rooms
- OOO Rooms
- Pax
- revenue_diff
- Room Revenue
weight_decay: 0.0
x_categoricals: []
x_reals:
- time_idx
- Total Room Inventory
- Rooms Sold
- Arrival Rooms
- Compliment Rooms
- House Use
- Individual Confirm
- Occupancy %
- ARR
- Departure Rooms
- OOO Rooms
- Pax
- revenue_diff
- Room Revenue
